server:
  port: 8081
spring:
  application:
    name: "SolicitudesService"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  sql:
    init:
      mode: "always"
adapters:
  driven:
    r2dbc:
      host: "localhost"
      port: 5432
      database: "crediya_loan_db"
      username: "rponce"
      password: null
      schema: "public"
  entry-points:
    rest-consumer:
      authentication-service:
        url: http://localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8081"
springdoc:
  paths-to-match: "/api/**"
adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:8081"
jwt:
  secret: "EsteEsUnSecretoSuperLargoYComplejoParaCrediYaQueDebeSerCambiadoEnProduccion12345"
  expiration-ms: 3600000
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
